### ISSUE TITLE
Add support to DASH

### ISSUE THREAD

**Issue by uliporeggia** [dutu/poloLender#10]
Thanks for this very useful project! Is possible to add DASH support?
Also, can you provide an wallet for me to pay you a beer? 😄

**Comment by dutu** [comment]
@uliporeggia, DASH support has been added, please update your client with the new revision.
If you wish to buy me a beer you can make a small donation here 15c91dGPndFPburMdtQZygQSoWxx1yUqyv.
Thanks

**Comment by uliporeggia** [comment]
Thanks!
https://blockchain.info/tx/55cc241d034961cdbc7e090a616482625ebd49b1ca561b38961f450e668939b7

**Comment by dutu** [comment]
Thanks @uliporeggia, appreciated
