### ISSUE TITLE
Problem after upgrading to new version

### ISSUE THREAD

**Issue by demeo** [dutu/poloLender#102]
[demeo@s3]:<~/polomama/poloLender>$ npm start

> poloLenderPro@1.0.0 start /usr/home/demeo/polomama/poloLender
> node -r babel-register app.js

module.js:327
    throw err;
    ^

Error: Cannot find module 'babel-register'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at module.js:497:12
    at Array.forEach (native)
    at Function.Module._preloadModules (module.js:496:12)
    at Function.startup.preloadModules (node.js:930:38)
    at startup (node.js:118:17)
    at node.js:1043:3

npm ERR! FreeBSD 10.3-STABLE
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v4.8.2
npm ERR! npm  v4.0.5
npm ERR! code ELIFECYCLE
npm ERR! poloLenderPro@1.0.0 start: `node -r babel-register app.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the poloLenderPro@1.0.0 start script 'node -r babel-register app.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the poloLenderPro package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node -r babel-register app.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs poloLenderPro
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls poloLenderPro
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/home/demeo/polomama/poloLender/npm-debug.log

any help? :)

**Comment by dutu** [comment]
Can you provide the log from npm install?

**Comment by dutu** [comment]
Please also Make sure you have the latest version of node.js installed.
You are running node v4.8.2, higher revision is required by this app.
