### ISSUE TITLE
config.json is not ignored nor tracked

### ISSUE THREAD

**Issue by ibjeong** [dutu/poloLender#104]
The new version saves the configuration to config.json, which is not .gitignore'd nor tracked.

It's not causing any problem but better to be ignored i think as .env* were.

**Comment by dutu** [comment]
@kukyakya, yes git is not tracking `config.json` and this is by purpose. 
Firstly, it ensures that your own `config.json` is not overwritten when you update the application code next time you update your application (hence your configuration settings will be kept)
Secondly, it ensures your own `config.json` is not uploaded to github if you use a fork of the application.

Unless you add the `config.json` manually to git (which you shouldn't do), it doesn't necessarily need to be added to `.gitignore` (but it doesn't hurt if it is - so I can add it when I upgrade the app version).

**Comment by dutu** [comment]
`config.json` added to `.gitignore` starting with version 1.1.0
