### ISSUE TITLE
do not get a telegram message.

### ISSUE THREAD

**Issue by sungjun001** [dutu/poloLender#105]
I use new version 1.0.0.

I save config with telegram token, userid. 

but I do not get a telegram message.

when I did use old version, I get a telegram message. 

why I do not get it?

**Comment by dutu** [comment]
Pls also make sure you check the box "enable telegram reports"

**Comment by sungjun001** [comment]
I already set up. but I do not get a telegram message.

**Comment by dutu** [comment]
@sungjun001, please double-check your telegram settings. The app seems to be working fine
