### ISSUE TITLE
Negative Performance Values

### ISSUE THREAD

**Issue by edgaru** [dutu/poloLender#108]
![image](https://user-images.githubusercontent.com/3507202/28532699-2c42ec40-7060-11e7-9f8e-ac15098f0a93.png)
It´s normal? The bot never starts working.

Thanks in advance.

**Comment by dutu** [comment]
Your current balance shows zero, which explains the negative performance displayed. Please check your API keys, check console log for errors and also make sure your funds are in poloniex lending account (not exchange or margin account)

**Comment by edgaru** [comment]
My XRP was on Exchange, thank you.

![image](https://user-images.githubusercontent.com/3507202/28533139-a7067f9a-7061-11e7-835a-a766d3384915.png)
