### ISSUE TITLE
Donate Button and ticker / counter in program?

### ISSUE THREAD

**Issue by abclution** [dutu/poloLender#109]
Thanks for the great program, unfortunately I am incredibly lazy and/or blind.

I cannot find the donate button / information anywhere, as well as I think it should be somewhere in the program as well. 
Plx halp thx

**Comment by dutu** [comment]
Thank you for your suggestion. What do you mean by "ticker / counter"?

**Comment by abclution** [comment]
Just something that keeps the people that donate updated. I could of course look up the wallet myself, but keeping the users / donaters involved in costs is very community friendly.
----------------------------------------------------------------------------------------
Total donations since $date, $blockchainlookupofdonationpubkey, * currency conversion
Monthly costs for services, =

**Comment by abclution** [comment]
Maybe also make your statistical analysis data availiable for donators or something too. 
For example I would be interested in running a backup/mirror of safe-holows-crypto.zone as a community service.

**Comment by dutu** [comment]
added in release 1.2.0
