### ISSUE TITLE
notice: returnActiveLoans: Poloniex error 422

### ISSUE THREAD

**Issue by rTreutlein** [dutu/poloLender#11]
I get a lot of these messages but I am not sure if that is a problem. I do have some active loans but no open loans or other coins in the lending account.

**Comment by dutu** [comment]
Would you please create a new API key and check if error persists?

**Comment by rTreutlein** [comment]
That fixed it thanks. Can you explain why the old key didn't work?

**Comment by dutu** [comment]
The 422 (Unprocessable Entity) status code is directly reported by Poloniex server. It means the server understands the content type of the request entity, and the syntax of the request entity is correct, but was unable to process the contained instructions. 

Nevertheless, I'm not sure why Poloniex returns error 422 or what is wrong with old APY keys.

**Comment by edmondja** [comment]
Hello, it solved my problem for 10 minutes then it didnt work anymore to create new secret keys.
Can somebody help me ?
