### ISSUE TITLE
CLAM not being monitored?

### ISSUE THREAD

**Issue by xR2** [dutu/poloLender#113]
I notice none of my CLAM is being lend, when I go to the Status tab, it's neither being monitored.
On poloniex however i see offers on 0.05% (quiet a nice rate).

![untitled57](https://user-images.githubusercontent.com/17341234/28990823-70c62db4-7957-11e7-84b2-b874ba64a005.png)

**Comment by dutu** [comment]
@xR2 CLAM support has been temporary suspended as per note below:

> Note: As of July 25, support for lending XMR, XRP, ETH and CLAM is temporary suspended. This is due low lending rates for these particular currencies and also the need of resources to keep lending support active (funds and computing power).  

CLAM rates are  still extremely low (~0.003%). I can reconsider allocating resources to support lending when rates will be higher.
