### ISSUE TITLE
XMR monitoring

### ISSUE THREAD

**Issue by vr0** [dutu/poloLender#114]
Is it possible to add XMR to the adivstor/monitoring?

Kind regards,
vr0

**Comment by dutu** [comment]
@vr0 XMR support has been temporary suspended as per note below:

> Note: As of July 25, support for lending XMR, XRP, ETH and CLAM is temporary suspended. This is due low lending rates for these particular currencies and also the need of resources to keep lending support active (funds and computing power).  

XMR rates are  still extremely low (0.0001%). I can reconsider allocating resources to support lending when rates will be higher.

**Comment by jkelly99** [comment]
XMR rates have recovered significantly. Could you add it back in?
