### ISSUE TITLE
Application crashing at start

### ISSUE THREAD

**Issue by Guegui** [dutu/poloLender#122]
Hi,

Whenever i start my application I get an error. (see attached picture)

I start with npm start and it says that poloender is restarting.

![command prompt](https://user-images.githubusercontent.com/29279752/33048246-dfe575a4-ce27-11e7-907f-242806f01a37.jpg)

**Comment by Guegui** [comment]
BTW, win10

**Comment by dutu** [comment]
Please check your configuration settings for startBalance

**Comment by Guegui** [comment]
Yeah i figured it was the problem, but how do i change the start balance if i dont have access to the web interface?

Also, what could be causing the issue with the start balance?  Thanks

**Comment by Guegui** [comment]
Nevermind, found it, just edit the config.json you should see the start balance there. Haven't figured out whats wrong in my start balance though

**Comment by dutu** [comment]
you can also delete `config.json` and the app will create a default file.
You should than set new config settings through gui
