### ISSUE TITLE
seems not work correct

### ISSUE THREAD

**Issue by flufy3d** [dutu/poloLender#13]
always at 5% 60days
info: Loan offered  #382095222 BTC     0.78305700 at 5.000000% (1825.00%), duration 60 days

**Comment by dutu** [comment]
There seems to be an issue with recent poloniex server changes for DDOS protection which are also impacting on poloLender advisor. 

I'll push a fix soon

**Comment by flufy3d** [comment]
thanks dutu

**Comment by dutu** [comment]
should be working now. 
I apologize for the inconvenience
