### ISSUE TITLE
Timeouts every few secounds

### ISSUE THREAD

**Issue by SearchAndDestroy** [dutu/poloLender#15]
I am getting these timeouts every few seconds:
notice: returnAvailableAccountBalances: ESOCKETTIMEDOUT
notice: returnActiveLoans: ETIMEDOUT
notice: returnOpenLoanOffers: ETIMEDOUT
notice: returnActiveLoans: ESOCKETTIMEDOUT
notice: returnActiveLoans: ETIMEDOUT
notice: returnOpenLoanOffers: ETIMEDOUT
notice: returnActiveLoans: ESOCKETTIMEDOUT
notice: returnAvailableAccountBalances: ETIMEDOUT
notice: returnAvailableAccountBalances: ETIMEDOUT
notice: returnOpenLoanOffers: ETIMEDOUT
notice: returnActiveLoans: ESOCKETTIMEDOUT
notice: returnOpenLoanOffers: ESOCKETTIMEDOUT
notice: returnAvailableAccountBalances: ETIMEDOUT
notice: returnActiveLoans: ETIMEDOUT
notice: returnOpenLoanOffers: ETIMEDOUT
notice: returnOpenLoanOffers: ESOCKETTIMEDOUT
notice: returnActiveLoans: ETIMEDOUT
notice: returnActiveLoans: ESOCKETTIMEDOUT
notice: returnOpenLoanOffers: ESOCKETTIMEDOUT
notice: returnOpenLoanOffers: ETIMEDOUT
notice: returnOpenLoanOffers: ETIMEDOUT

The bot creates  and get returned loans without problems though.
It's running locally on my machine and I created a new API key for it.

**Comment by dutu** [comment]
@SearchAndDestroy, these are transient Poloniex server errors. 

We see these errors every now and than when Poloniex is having issues with their servers. I'd nothing we can do about it, just ignore the bot is handling these errors, and places the loans correctly even with these transient errors. 

For reference you can also check https://github.com/dutu/poloniex-api-node/issues/4, reporting Poloniex API issues.
