### ISSUE TITLE
createLoanOffer: Amount must be at least 0.01

### ISSUE THREAD

**Issue by VinnyR** [dutu/poloLender#16]
Hello,

I've started to get these messages in the log about every 1s:

createLoanOffer: Amount must be at least 0.01

I logged into Poloniex and checked my balance. It is less than 0.01, and it won't allow me to manually offer this amount. 

Is this the normal operation of the bot?

**Comment by dutu** [comment]
Thanks for reporting it. Poloniex have recently changed the limit from 0.001 to 0.01. I have nou updated the app. Please update to 0.7.1
