### ISSUE TITLE
Poloniex error 422: Nonce must be greater than .....

### ISSUE THREAD

**Issue by VinnyR** [dutu/poloLender#19]
Today I started to get the error:

Poloniex error 422: Nonce must be greater than *****. You provided *****. 

(I have hidden the actual nonce values for security reasons). I also started to frequently get the error:

Poloniex error 429: Please do not make more than 8 API calls per second. 

With poloLender 0.7.1, I usually only get error 429 about every 90 minutes or less, which doesn't seem to be problematic. But for some reason I got error 429 multiple times today within a couple of seconds. Sorry if I should have kept error 429 as a separate issue but I don't know if it's related. I also received this error message:

Poloniex error 429: This IP has been temporarily throttled. Please ensure your requests are valid and try again.

I've attached a small portion of the log in an excel file. I assume this may be an issue with poloniex server but perhaps there is a way poloLender can handle these situations?

Kind regards,

[log3.xlsx](https://github.com/dutu/poloLender/files/925813/log3.xlsx)

**Comment by dutu** [comment]
Please generate and use a new API key

**Comment by VinnyR** [comment]
Thanks, I'm now using a fresh API key. It's been an hour and no error messages so far. I'll report back in a few days.

Kind regards,

**Comment by VinnyR** [comment]
Hello,

I haven't received the error since using a new API key. It seems to have solved the problem.

**Comment by tayareci** [comment]
İ couuldnt it. Similar error but again same error after new created API

**Comment by hems** [comment]
@tayareci sometimes the statusCode 422 can happen for other reasons as well, check the object returned by Poloniex API in order to see what is happening, sometimes it's just an invalid parameter you are sending

**Comment by nsnikolaev** [comment]
I have: "Poloniex error 422: . Nonce must be greater than 1573038171160165. You provided 157719741402400."
1573038171160165 - is 16 digits
157719741402400 - is 15 digits

What this????
