### ISSUE TITLE
Nonce issue

### ISSUE THREAD

**Issue by svenwoldt** [dutu/poloLender#2]
I was looking throught your code for the following error callback of poloniex.

notice: returnActiveLoans: Nonce must be greater than 1432780392338378. You provided 147013733967300.

Could not reason entirely as to how to slow your api calls to the acceptable threshold.
Would you know about it? Is this known to you?
Regards

**Comment by dutu** [comment]
this "notice" can be ignored. The bot is handling the situation correctly and there is no need to worry.

Possible way to resolve this is by implementing a handling queue for all API requests. In my view it's not worth the effort as there would be no real gains.
Probably you could switch of warning console output if it's too annoying

**Comment by dutu** [comment]
the API calls are executed in series, each one running once the previous function has completed.
The error should only occur once in a while and when occurs it can be ignored.

If you see this error continuously, please generate and use new API key.
