### ISSUE TITLE
Feature Request: status page could provide a short summary with info like total balance + amount currently being lended ...

### ISSUE THREAD

**Issue by abletaz** [dutu/poloLender#29]
and open orders, average interest rate, information on returns, etc ....

**Comment by stranger29** [comment]
I believe that before this should be implemented, some sort of auth must be added.
As IMHO one doesn't want to show his assets value to the whole world.
something as simple as username and 4 digit pin should be good enough

**Comment by dutu** [comment]
included in version 0.11.0
