### ISSUE TITLE
Module 'request'

### ISSUE THREAD

**Issue by anazhd** [dutu/poloLender#3]
For some reason, after reinstalling poloLender on different pc/server, module 'request' is not available which I have to install manually by using `npm install request --save`

It wasn't required before. I don't know why.

**Comment by michel5** [comment]
Request is not in the list package.json . Create a pull request for it to.

**Comment by anazhd** [comment]
Do you know which version of request should i include ?

**Comment by michel5** [comment]
Does not matter. The latest version is fine. Which OS do you run on your PC ?

**Comment by anazhd** [comment]
I run on 2 pc, ubuntu 16.04 and windows 10 x64. Both required requests.

**Comment by michel5** [comment]
https://github.com/micheldaniel/poloLender

take this version. I have update de package.json file. 

BTC DONATION: 1PeL2CWrLbggqdHF2X85dgieiNQQYRdD7v

**Comment by dutu** [comment]
thanks @anazhd and @micheldaniel 
fixed with https://github.com/dutu/poloLender/commit/12b57cfc711fdcd74fc94ab89a505c491ca83bbf (0.3.1)
