### ISSUE TITLE
safe-hollows.crypto.zone

### ISSUE THREAD

**Issue by bradburycode** [dutu/poloLender#37]
Hi,

Is there a problem with safe-hollows.crypto.zone  ?
There doesn't seem to be any data at the moment. :(

![image1](https://cloud.githubusercontent.com/assets/24245578/26037557/5808e1e0-38ed-11e7-9129-d917e6092395.png)

http://pho.to/AhICW

Thanks in advance.

**Comment by dutu** [comment]
Seemed to be a temporary situation. It looks OK now. Can you confirm?

**Comment by bradburycode** [comment]
Looks like it is working perfectly.

thank you for all your great work.  

![image1](https://cloud.githubusercontent.com/assets/24245578/26047852/bb1a6b3c-394c-11e7-8551-03f63260b810.png)
