### ISSUE TITLE
package.json not JSON

### ISSUE THREAD

**Issue by oyerpes** [dutu/poloLender#39]
Hello,

Trying to "npm install" on my computer throws this error:

npm install
npm ERR! Linux 3.10.0-514.16.1.el7.x86_64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! node v6.10.2
npm ERR! npm  v3.10.10
npm ERR! file [..]/.npm/big.js/3.1.3/package/package.json
npm ERR! code EJSONPARSE

npm ERR! Failed to parse json
npm ERR! No data, empty input at 1:1
npm ERR! 
npm ERR! ^
npm ERR! File: [..]/.npm/big.js/3.1.3/package/package.json
npm ERR! Failed to parse package.json data.
npm ERR! package.json must be actual JSON, not just JavaScript.

Any ideas?

Kind regards,

**Comment by dutu** [comment]
can you do `npm cache clean` and try `install` again?

**Comment by oyerpes** [comment]
Worked like a charm. Thanks dutu!

Regards,
