### ISSUE TITLE
Feature Request: Lending Rate History

### ISSUE THREAD

**Issue by godfrey22** [dutu/poloLender#42]
Hi, is it possible to record the best lending rate by a given interval, which can be set in the config?

**Comment by dutu** [comment]
@godfrey22, can you please detail a bit moire? Should the best lending rate for a given period be displayed only? Or are you suggesting it should be used in a certain way (and if yes how should it be used?)

**Comment by godfrey22** [comment]
For instance, I can set the interval for 1 min. So that, in every minute (12:00, 12:01...) the best lending rate could be recorded in a csv maybe. If I set it to 1 hour, every hour(12:00, 13:00...) the best lending rate could be recorded.
The reason being, the spike happens around second week(kind of) each month, but I really could not track it and prove it. If the program could track it 24/7, and we could use the data to visualize it and adjust the lending rate much more efficient.

**Comment by dutu** [comment]
@godfrey22,  ok thanks, it's still not very clear if you want to just display the best lending rate or you want to include this data for the bot to "adjust the lending rate much more efficient.". Do you have a proposal/suggestion on how you would like to have it done?

The lending server already keeps track of the best return rates during the last 48 hours and uses this data in conjunction with the average loan holding time to calculate the best return rate. 

The average loan holding time is normally between 1-12 hours. As such, looking at data from several weeks/days back, has not much relevance. Surly you will be less efficient if you keep waiting for a better loan which may come in several days time.

**Comment by godfrey22** [comment]
@dutu It will be great if it can display the best lending rate over time as a chart on the web interface. But I really hope it can display the rate in a wide range of time.
The main reason was that, I found that whenever there were spikes or the average rate is higher than normal, the altcoins price rises in the next week. So I am guessing borrowed bitcoin goes to the margin trade, the spike means people are borrowing bitcoin to long altcoin which was a indication of potential rise of price for altcoin in the next week. (All these are guessing, need the data to prove it)
By tracking the lending rate, I want it to improve my trading strategy in the future. Since the bot receives the best lending rate every few minutes, so i guess it won't be too hard to generate a rate graph, right?

**Comment by dutu** [comment]
@godfrey22, this would be out of scope of a lending bot, but certainly a nice feature to have and I will consider it for a next release.
You could perhaps also use the data at https://www.bfxdata.com
