### ISSUE TITLE
is working? 

### ISSUE THREAD

**Issue by tsebis** [dutu/poloLender#43]
hello, i dont know if is really working fine, and i have some questions, i can pay if you help me...  i need disable or enable auto renew on polo?

**Comment by tsebis** [comment]
ok, auto renew need be disabled, if i buy the hobby plan, Can I turn off my computer?

**Comment by dutu** [comment]
@tsebis, just post your questions here, you'll get help, no problem. 

You should disable auto-renew for existing loans, before you start the bot. After that the bot will take care of everything. 

Yes, if you run the bot on heroku, you can turn off your home PC
