### ISSUE TITLE
Problem...

### ISSUE THREAD

**Issue by tsebis** [dutu/poloLender#44]
![image](https://cloud.githubusercontent.com/assets/20957523/26714951/245a062e-474a-11e7-96a9-39f292c28047.png)
Hey, see it,  Sometimes the bot creates orders far above the available values, and ends up being left a long time without being executed ... is it some field that I should correct?

**Comment by dutu** [comment]
It is a normal behaviour to wait for better rates. 
Please see detailed answer: here https://github.com/dutu/poloLender/issues/32
