### ISSUE TITLE
notice: returnOpenLoanOffers: Connection timed out. Please try again

### ISSUE THREAD

**Issue by tsebis** [dutu/poloLender#47]
Hello, why appear this error? notice: returnOpenLoanOffers: Connection timed out. Please try again

**Comment by dutu** [comment]
The error is returned when communicating with poloniex server. 
Poloniex API has been very instabile during the last couple of weeks and at times this error (and other error occur). 

The bot is handling the errors correctly, there is nothing to worry about.
