### ISSUE TITLE
Fix please..

### ISSUE THREAD

**Issue by tsebis** [dutu/poloLender#48]
Hello,
When the orders are usually at 0.30% for example, then it drops to 0.15%, the bot keeps opening at 0.30% and then we waste a lot of time with open orders ... can you fix it? I would like to donate in bitcoin, how do I?

**Comment by realprogrammerxD** [comment]
+1

**Comment by dutu** [comment]
The bot opens for a higher rate based on history of latest top rates and average loan holding time.
Only when the waiting for a higher rate is considered less profitable, the bot is offering the loan at lower rate.
The offered rate and waiting time are calculated to get the best possible return rate.
Note: when the average loan holding time is higher, the bot waits longer for a higher rate (as likely it's more profitable to wait longer for a higher rate). During periods when average loan holding time is short (let's say less then one hour) the bot will make offers at lower rates more rapidly.

Please also see https://github.com/dutu/poloLender/issues/30, and https://github.com/dutu/poloLender/issues/32

Let me know if explanation makes sense.

**Comment by dutu** [comment]
See [FAQ](https://github.com/dutu/poloLender/blob/master/faq.md)
