### ISSUE TITLE
Safe-hollow connection problems

### ISSUE THREAD

**Issue by Guegui** [dutu/poloLender#49]
I get errors from the safe-hollow server, that makes the bot unusable. Any ideas why and when its gonna be back up again?

By the way great work on your bot I like it a lot.

![2017-06-08 09_18_44-datpc - teamviewer - licence gratuite seulement pour l utilisation privee](https://user-images.githubusercontent.com/29279752/26930845-a59071a6-4c2c-11e7-9d32-1bf8d24d4d32.png)

**Comment by dutu** [comment]
should be fine now
