### ISSUE TITLE
Feature request: return by date

### ISSUE THREAD

**Issue by stranger29** [dutu/poloLender#50]
Ability to gracefully return all or part of lent funds by a specific date.
I.e. on May 1st we specified in the GUI that all funds must be returned no later than by June 1st
The app will limit lending to 31 days on May 1st, to 30 days on May 2nd etc.
During last two days, it won't lend anything.

This would be an amazing feature!

**Comment by dutu** [comment]
@stranger29, wouldn't be easy enough to just stop the bot when you want your funds not to be lent anymore?

**Comment by stranger29** [comment]
@dutu, not really as If I decide that I need funds back in a couple weeks, first I need to hardcode every day max duration, 2nd I need to remember to stop it no later than on X-2 date, which could be the most complicated part since I'm just a human :)
Also, usually I need only part of my funds as i.e. I want to participate in ICO or smth...

**Comment by dutu** [comment]
The bot always lends for 2 days. You'd just need to set a reminder in your calendar to stop the bot 2 days before you need the funds. 
If you only need part of your funds, set parameter POLOLENDER_LENDMAX instead of stopping it.

**Comment by stranger29** [comment]
@dutu, ok, got it, thx. I think it should be added to the FAQ (that bot always lends for 2 days)
