### ISSUE TITLE
Question: Bitfinex is in the roadmap ?

### ISSUE THREAD

**Issue by stranger29** [dutu/poloLender#53]
@dutu 
I was checking out the code and found some lines regarding Bitfinex. 
Is it in your plans?  Or it's just a code reusage? :)
I mean their fiat lending platform shows really good returns and I think they have 2nd largest lending pool after Poloniex.
Thx.

**Comment by dutu** [comment]
you see bitfinex in the code since the bot uses bitfinex BTC/USD rate to give profitability in USD, cause  Poloniex doesn't give USD rates.

Yes, several bots are in the roadmap and being finalized including Bitfinex lending and trading bots.
