### ISSUE TITLE
No connection to safe-hollows, no data in dashboard

### ISSUE THREAD

**Issue by patrickstorm** [dutu/poloLender#55]
I just tried firing this guy up and I am getting no data and the bot isn't making trade. Not sure what is up. Seeing this:
<img width="559" alt="screen shot 2017-06-13 at 4 57 23 pm" src="https://user-images.githubusercontent.com/1664793/27109748-8b442974-5059-11e7-9c7f-f40d86475acd.png">

**Comment by dutu** [comment]
can you give more details? please check the console log

**Comment by patrickstorm** [comment]
This is all that is in the console. 
```
info: Using POLOLENDER_REPORTINTERVAL=30
info: Using POLOLENDER_STARTTIME=Tue Feb 28 2017 04:27:09 GMT-0800
info: Using POLOLENDER_STARTBALANCE={"BTC":"10","ETH":"1100","XMR":"1000"}
info: Using POLOLENDER_LENDMAX={"BTC":"900","ETH":"99900","XMR":"2000"}
info: Using POLOLENDER_MINRATE={"BTC":"0","ETH":"0","XMR":"0","XRP":"0","LTC":"0"}
info: Using POLOLENDER_STARTTIME=2017-02-28T12:27:09Z
info: Listening on Port 5000
info: Loan taken    #203102272 BTC     0.16430108 at 0.183400% (66.94%), created 2017-06-13 21:54, expires in 2 days
info: Loan taken    #203083985 BTC     0.04495314 at 0.170700% (62.31%), created 2017-06-13 21:27, expires in 2 days
warning: Error connecting to server safe-hollows.crypto.zone (undefined: undefined)
info: Reconnecting to server safe-hollows.crypto.zone (1)
info: Reconnected to server safe-hollows.crypto.zone
notice: ♣ poloLender 0.8.2 running for 105 days • restarted a few seconds ago (2017-06-14 04:04) • Offers/Loans: 2/2  • speed: 0.00/min
```

I updated line 104 in content.js to log out the event and data
```
  socket.on('*', function (event, data) {
    console.log(event, data);
  });
```
This is what I see in the console::
![screen shot 2017-06-14 at 9 16 45 am](https://user-images.githubusercontent.com/1664793/27143210-7c7d38de-50e2-11e7-8c8e-1ff5584da602.png)

**Comment by patrickstorm** [comment]
After more investigation, the poloLender doesn't seem to be connecting properly to `http://safe-hollows.crypto.zone/`. I am never getting a `connect` and definitely never getting a `send:loanOfferParameters`

**Comment by patrickstorm** [comment]
This is all locally by the way, not sure if that changes anything, it works for me on Heroku

**Comment by dutu** [comment]
can you reach http://safe-hollows.crypto.zone/ from the browser?

**Comment by patrickstorm** [comment]
Yeah, although the page never populates with data
<img width="832" alt="screen shot 2017-06-14 at 11 35 56 am" src="https://user-images.githubusercontent.com/1664793/27148583-ab379576-50f5-11e7-83a1-7616e01c0879.png">

**Comment by dutu** [comment]
can you wait for a minute or so and check if the page populates with data.
It should look like this

![image](https://user-images.githubusercontent.com/6230798/27149011-df24f3b0-514a-11e7-81dc-524349255382.png)

**Comment by patrickstorm** [comment]
It's been open for almost 15 minutes, same as issue as above. I am seeing websocket transmissions in the network tab, so I'm not sure what is going on there

**Comment by dutu** [comment]
hm... so the issue is not with poloLeder app, since you cannot connect from the browser either.

**Comment by patrickstorm** [comment]
The odd thing is everything seems fine when it is running on Heroku.

**Comment by dutu** [comment]
the issue doesn't seem to be with the application. Are you perhaps behind a proxy which is restricting the traffic?

**Comment by patrickstorm** [comment]
No, I can try on a different computer later today though, maybe something in my environment is messing it up. If the issue is not reproducible, feel free to close this issue.

**Comment by dutu** [comment]
Please use the newly released v0.8.3 as it supposed to give print out the error message for the socket connection error. Maybe the error message can give more clues on where the issue can be

**Comment by dutu** [comment]
@patricktoerner, do you have any additional feedback and data so I can try to help you out or is your issue resolved?

**Comment by patrickstorm** [comment]
I have a feeling it is something on my dev environment since it works on heroku. The newest code isn't working for me and I'm not getting any more data in the console.

**Comment by dutu** [comment]
What details do you get in the message "error connecting to server"? 
BTW, there are 100+ clients connected to the server

**Comment by patrickstorm** [comment]
I get the following, and nothing else. I sometimes get an error that it couldn't connect to safe-hollows, but not always.
```
info: Using POLOLENDER_REPORTINTERVAL=30
info: Using POLOLENDER_STARTTIME=Tue Feb 28 2017 04:27:09 GMT-0800
info: Using POLOLENDER_STARTBALANCE={"BTC":"10","ETH":"1100","XMR":"1000"}
info: Using POLOLENDER_LENDMAX={"BTC":"900","ETH":"99900","XMR":"2000"}
info: Using POLOLENDER_MINRATE={"BTC":"0","ETH":"0","XMR":"0","XRP":"0","LTC":"0"}
info: Using POLOLENDER_STARTTIME=2017-02-28T12:27:09Z
info: Listening on Port 5000
info: Loan taken    #204529822 BTC     0.04510732 at 0.132499% (48.36%), created 2017-06-16 07:12, expires in a day
info: Loan taken    #204490201 BTC     0.69266325 at 0.099799% (36.43%), created 2017-06-16 04:34, expires in a day
info: Loan taken    #204348705 BTC     0.16481358 at 0.159295% (58.14%), created 2017-06-15 21:56, expires in a day
```

**Comment by dutu** [comment]
@patricktoerner it looks that the issue is with your environment and I have too little details to help you out.
The latest version of the code doesn't change any functionality regarding the connectivity, except that it'll show more details with the message `warning: Error connecting to server safe-hollows.crypto.zone`. That's the reason I asked for it, hopefully it shows additional information on why your connection cannot get through.
