### ISSUE TITLE
Min order amounts causing issues

### ISSUE THREAD

**Issue by patrickstorm** [dutu/poloLender#56]
Poloniex is adjusting minimum order amounts and it is causing issues with the poloLender app. See the image below: 
<img width="736" alt="screen shot 2017-06-14 at 12 12 58 pm" src="https://user-images.githubusercontent.com/1664793/27150155-e7ad7354-50fa-11e7-9886-025fbd01d16f.png">

The big problem with this is that the poloLender stops iterating through the altcoins when this happens, so the altcoins after the current one never get loan offers created.

I would propose another config variable in the defaultConfigs that has Poloniex's min order amount for each coin, then check that before attempting to create the offer. In addition, I think we will need to remove some of the `return` statements because it is stopping the loop from reaching the other currencies.

I can create a PR later today, I just wanted to get this issue out.

**Comment by dutu** [comment]
@patricktoerner, thank you for reporting the issue.
yes, Poloniex has recently set different minimum amounts for currencies and we should have these defined in the  defaultConfigs accordingly.

From what I see even if the error is encountered, it shudn't prevent the app to iterate to next currency. We pass `null` when calling the callback  here https://github.com/dutu/poloLender/blob/master/server/workers/poloLender/poloLender.js#L510
hence `async.forEachOfSeries` iterates to next currency.

**Comment by patrickstorm** [comment]
My logs show this:
<img width="1031" alt="screen shot 2017-06-14 at 12 56 15 pm" src="https://user-images.githubusercontent.com/1664793/27151906-ea5eab94-5100-11e7-9509-32181b9eb914.png">

There was 25000 DOGE and .09 ETH in my lending account. I was getting the `notice: createLoanOffer: Amount must be at least 1.` for 15 minutes straight, then when I transfered the ETH out of my lending account, the DOGE loan offer was placed.

**Comment by dutu** [comment]
You're right.
Since the error is returned by the API, the callback called with the an error, hence it doesn't iterate to next currency

**Comment by dutu** [comment]
@patricktoerner, I'll send the minOrderAmount from the server so that we don't have to update the client code every time Poloniex is changing the value

**Comment by patrickstorm** [comment]
Great idea 👍

**Comment by dutu** [comment]
fixed in version 0.8.3. 
I'd appreciate if you let me know if it works for you

**Comment by patrickstorm** [comment]
That fixed it. All working for me now. Thanks @dutu
