### ISSUE TITLE
notice: cancelLoanOffer: Error canceling loan order, or you are not the person who placed it.

### ISSUE THREAD

**Issue by stranger29** [dutu/poloLender#58]
Hello, thanks for the update !
I've just updated to version 0.8.3 and got this error, never had one like this on 0.8.2.
Please feel free to close it if it's not a bug.

**Comment by dutu** [comment]
@stranger29, it's not a bug, it's version independent and it can be seen occasionally.
When the bots tries to place a loan offer at a different rate the following steps are done one after the other:
1. get open loan offers
2. cancel offers
3. place new offer at different rate

If your loan offer is taken exactly between 1 and 2 the message you're mentioning can be seen.

It's nothing to worry about and it can can happen from time to time.
Hope the explanation makes sense.

**Comment by stranger29** [comment]
@dutu Sure, thx for explanation, it's just the first time I saw it, considering how slow poloniex is working now, it's absolutely possible
