### ISSUE TITLE
telegram to message

### ISSUE THREAD

**Issue by mostechlee** [dutu/poloLender#59]
I modified logger.js
using node-telegram-bot-api
but only [info] message to me.
how can I receive all message?
 
```
use strict;
var winston = require(“winston”);
require(‘winston-telegram’).Telegram;
 
var logger = new (winston.Logger)({
       transports: [
              new (winston.transports.Telegram) ({
                  token : ‘bot token’,
                  chatId : ‘user_id’,
                  unique : true
 
              }),
 
              new (winston.transports.Console)({
                  colorize: ‘all’
 
              })
 
                   ]
 
  });
 
module.exports = logger;

```

**Comment by dutu** [comment]
@mostechlee, you'd need to setup a telegram bot, see [How do I create a bot](https://core.telegram.org/bots). and then use in the logger setup the details you receive. Let me know how it goes

**Comment by mostechlee** [comment]
The bot is already running.
Now, only [info] messages appear.
I want all the messages to come out of the telegram as on the console.
Thank you for help

**Comment by dutu** [comment]
Thanks for your feedback. 
Use parameter `level` when you define your telegram transport
https://www.npmjs.com/package/winston-telegram

**Comment by dutu** [comment]
... and set `unique` to `false`

**Comment by mostechlee** [comment]
unique to false option is all...
Thank you  very much!

**Comment by dutu** [comment]
the newly release version 0.9.0 support sending the reports to your telegram messenger.

Note that only the reports are sent and not all "info" messages for individual loans.

Hope you'll enjoy the feature as implemented
