### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by tsebis** [dutu/poloLender#62]
Hello, possible you add, the average percentage of our loans? For example, you have 4 loans, 2 of 15% and 2 of 17% so the bot would report that our average loan percentage is 16%

**Comment by dutu** [comment]
The bot reports the "wmr" which is the "weighted mean rate". It is the average percentage you are describing above and it also takes into consideration the amount (weight) of each loan.

Additionally, the bot reports the "ewmr", which is the "Effective weighted mean rate" calculated as wmr minus the 15% taken as commission by Poloniex. This is your net profit.
(Note that the rate in parenthesis is the annual rate equivalent - as simple rate, not compounded)

Hope this is fine and the number presented are relevant for your request.

**Comment by tsebis** [comment]
What is brr in the log?

**Comment by dutu** [comment]
brr is best-return rate

**Comment by shaor0x** [comment]
What is alht in the log ?

**Comment by dutu** [comment]
average loan holding time
