### ISSUE TITLE
What the (XX,X%) after the interest means ?

### ISSUE THREAD

**Issue by shaor0x** [dutu/poloLender#65]
Hi!
Im running the bot on a EC2 Windows on AWS, and i have a few questions.

What the (XX,X%) after the interest means ?
info: Loan taken    #205364535 BTC     0.05364330 at 0.187000% (**68.26%**), created 2017-06-17 14:58, expires in a day.
Note: this loan in case was made by another BOT. Its just your bot showing it.

**Comment by dutu** [comment]
that the rate in parenthesis is the annual rate equivalent - as simple rate, not compounded.

The bot will show all loans taken, not only the ones placed by the bot itself.

**Comment by shaor0x** [comment]
Ok thanks!
Im setting up the bot, and soon everything is fine i will make a video in pt-br to show our community how it works and how to get it running. If you are interested in some way i send send you the link.

**Comment by dutu** [comment]
Thank you, @shaor0x, that would be very nice and useful. If you send me the link I will include it in the Readme for everyone to access it easier.
