### ISSUE TITLE
Run like worker

### ISSUE THREAD

**Issue by festrs** [dutu/poloLender#68]
It's possible to run just the lending part with node-schedule as worker? #

**Comment by dutu** [comment]
I don't quite understand the question, would you please detail it a bit?

**Comment by festrs** [comment]
Sorry, because Heroku will stop u web application after a short period of time, why don't work with (https://devcenter.heroku.com/articles/background-jobs-queueing) workers, can schedule a job and don't interfere with Heroku shutdown time.

**Comment by dutu** [comment]
@festrs, I'll add the solution to accommodate the request in the next release.
If you need the change immediately, you should modify the file `Procfile` and replace its content with:
```
web: node server.js
worker: node server.js
``` 

Once you have modified the file,   push the changes to Heroku, go to your Heroku dashboard, stop the web dyno and start the worker dyno.

![image](https://user-images.githubusercontent.com/6230798/27331945-76419b78-55c8-11e7-84e3-3cfadb4ac7ec.png)

> Note: with a Free Heroku plan, even your worker dyno will stop after your [free dyno monthly hours](https://devcenter.heroku.com/articles/free-dyno-hours#usage) have been consumed.

**Comment by dutu** [comment]
added in version 0.10.0
