### ISSUE TITLE
Guide not working...

### ISSUE THREAD

**Issue by tsebis** [dutu/poloLender#69]
Your guide how to update the application in heroku does not work

**Comment by dutu** [comment]
Please give more details on the steps you're following, where you get stuck and short description of the issue.

**Comment by tsebis** [comment]
worked now... i've changed my app name before... how i can send the notifications to my telegram? any guide?

**Comment by tsebis** [comment]
my bad, my app still  0.8.3...
i do it: open the cmd > cd poloLender > git pull origin master > heroku addons:open papertrail > git push heroku master

**Comment by dutu** [comment]
can you provide the log 
Pleases see the [FAQ ](https://github.com/dutu/poloLender/blob/master/faq.md)on how to setup telegram

**Comment by tsebis** [comment]
C:\Users\acer-i5\poloLender>git push heroku master
Counting objects: 25, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (23/23), done.
Writing objects: 100% (25/25), 3.32 KiB | 0 bytes/s, done.
Total 25 (delta 14), reused 0 (delta 0)
remote: Compressing source files... done.
remote: Building source:
remote:
remote: -----> Node.js app detected
remote:
remote: -----> Creating runtime environment
remote:
remote:        NPM_CONFIG_LOGLEVEL=error
remote:        NPM_CONFIG_PRODUCTION=true
remote:        NODE_VERBOSE=false
remote:        NODE_ENV=production
remote:        NODE_MODULES_CACHE=true
remote:
remote: -----> Installing binaries
remote:        engines.node (package.json):  ^7.7.4
remote:        engines.npm (package.json):   ^4.1.1
remote:
remote:        Resolving node version ^7.7.4 via semver.io...
remote:        Downloading and installing node 7.10.0...
remote:        Resolving npm version ^4.1.1 via semver.io...
remote:        Downloading and installing npm 4.6.1 (replacing version 4.2.0)...
remote:
remote: -----> Restoring cache
remote:        Loading 2 from cacheDirectories (default):
remote:        - node_modules
remote:        - bower_components (not cached - skipping)
remote:
remote: -----> Building dependencies
remote:        Installing node modules (package.json)
remote:
remote: -----> Caching build
remote:        Clearing previous node cache
remote:        Saving 2 cacheDirectories (default):
remote:        - node_modules
remote:        - bower_components (nothing to cache)
remote:
remote: -----> Build succeeded!
remote: -----> Discovering process types
remote:        Procfile declares types -> web
remote:
remote: -----> Compressing...
remote:        Done: 23.1M
remote: -----> Launching...
remote:        Released v25
remote:        https://arcane-lowlands-29442.herokuapp.com/ deployed to Heroku
remote:
remote: Verifying deploy.... done.
To https://git.heroku.com/arcane-lowlands-29442.git
   23b4f43..ddbbf87  master -> master

**Comment by dutu** [comment]
Please provide the log of these commands: cmd > cd poloLender > git pull origin master > heroku addons:open papertrail > git push heroku master

**Comment by tsebis** [comment]
C:\Users\acer-i5>cd poloLender

C:\Users\acer-i5\poloLender>git pull origin master
remote: Counting objects: 30, done.
remote: Compressing objects: 100% (14/14), done.
remote: Total 30 (delta 18), reused 26 (delta 14), pack-reused 0
Unpacking objects: 100% (30/30), done.
From https://github.com/dutu/poloLender
 * branch            master     -> FETCH_HEAD
   ddbbf87..93cc355  master     -> origin/master
error: Your local changes to the following files would be overwritten by merge:
        .env-template
Please commit your changes or stash them before you merge.
Aborting
Updating ddbbf87..93cc355

C:\Users\acer-i5\poloLender>heroku addons:open papertrail 
Opening https://addons-sso.heroku.com/apps/...

C:\Users\acer-i5\poloLender>git push heroku master
Counting objects: 25, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (23/23), done.
Writing objects: 100% (25/25), 3.32 KiB | 0 bytes/s, done.
Total 25 (delta 14), reused 0 (delta 0)
remote: Compressing source files... done.
remote: Building source:
remote:
remote: -----> Node.js app detected
remote:
remote: -----> Creating runtime environment
remote:
remote:        NPM_CONFIG_LOGLEVEL=error
remote:        NPM_CONFIG_PRODUCTION=true
remote:        NODE_VERBOSE=false
remote:        NODE_ENV=production
remote:        NODE_MODULES_CACHE=true
remote:
remote: -----> Installing binaries
remote:        engines.node (package.json):  ^7.7.4
remote:        engines.npm (package.json):   ^4.1.1
remote:
remote:        Resolving node version ^7.7.4 via semver.io...
remote:        Downloading and installing node 7.10.0...
remote:        Resolving npm version ^4.1.1 via semver.io...
remote:        Downloading and installing npm 4.6.1 (replacing version 4.2.0)...
remote:
remote: -----> Restoring cache
remote:        Loading 2 from cacheDirectories (default):
remote:        - node_modules
remote:        - bower_components (not cached - skipping)
remote:
remote: -----> Building dependencies
remote:        Installing node modules (package.json)
remote:
remote: -----> Caching build
remote:        Clearing previous node cache
remote:        Saving 2 cacheDirectories (default):
remote:        - node_modules
remote:        - bower_components (nothing to cache)
remote:
remote: -----> Build succeeded!
remote: -----> Discovering process types
remote:        Procfile declares types -> web
remote:
remote: -----> Compressing...
remote:        Done: 23.1M
remote: -----> Launching...
remote:        Released v25
remote:        https://arcane-lowlands-29442.herokuapp.com/ deployed to Heroku
remote:
remote: Verifying deploy.... done.
To https://git.heroku.com/arcane-lowlands-29442.git
   23b4f43..ddbbf87  master -> master

C:\Users\acer-i5\poloLender>

**Comment by dutu** [comment]
You have modified the `.env-template` file on your computer and `git pull` command failed to overwrite it.

I have now updated the instruction to overwrite all modified files. 
Let me know if it works.

**Comment by tsebis** [comment]
I did it again, step by step, now it worked, thank you.

**Comment by tsebis** [comment]
![image](https://user-images.githubusercontent.com/20957523/27304828-b58418fa-5515-11e7-8f36-0b57bd4e00a9.png)
When I updated the application, these two variables were not created automatically, I did this manually is correct? So far I have not received any notifications on my telegram

**Comment by dutu** [comment]
The variables are not created automatically.
Can you open the you created in telegram (you can search by its name) and see if you receive new reports

**Comment by tsebis** [comment]
![image](https://user-images.githubusercontent.com/20957523/27305605-a3e034c8-5518-11e7-9248-0ea888ea6bc2.png)
 any report there

**Comment by tsebis** [comment]
and have a new report in papertrail info: Loan returned #206629554 BTC     0.00426348 at 0.168699% (61.58%), holding time: 8h 10m 20s

**Comment by dutu** [comment]
@tsebis,  only the regular reports (with total amount of coins in your account and profitability) are sent to Telegram. The "info" messages for individual loans are not.

**Comment by tsebis** [comment]
ah ok, lets wait
