### ISSUE TITLE
new version error

### ISSUE THREAD

**Issue by persona35** [dutu/poloLender#70]
I update pololender to recent version and set up telegram variable. 

When I start pololender, I encountered the messages below.  

![2017-06-20 08 31 27](https://user-images.githubusercontent.com/10555715/27310137-170d77e2-5593-11e7-9fe5-b68479d563f2.png)

After I erase telegram setting variable, the error still coming.

**Comment by stranger29** [comment]
Have you done npm update ?

**Comment by persona35** [comment]
Yes, I followed update procedure step by step.
But, I still have same error message.

After that, I delete previous program, and install new one from the scratch step by step.

And I still have same error message.

my system is ubuntu 14.04.1

**Comment by persona35** [comment]
I solved this problem. 
The version of node.js was 6.x, I update node.js to 8.x and the problem was gone. 

Thanks.
