### ISSUE TITLE
notice: bfxPublic.ticker: 502

### ISSUE THREAD

**Issue by shaor0x** [dutu/poloLender#71]
Hi!

From time to time im getting this error: notice: bfxPublic.ticker: 502

The bot still works, but im getting this error on the old verson and in the new. What this error means ?

**Comment by stranger29** [comment]
It means that Bitfinex API servers can not handle your request atm.

**Comment by shaor0x** [comment]
Its a poloniex lender, why im getting connected to bitifinex ?

**Comment by stranger29** [comment]
@shaor0x 
Please see https://github.com/dutu/poloLender/issues/64
It uses bitfinex to get btc/usd rate

**Comment by alejandrolechuga** [comment]
is the same as `notice: bfxPublic.ticker: Error: 429` right ? seems like an HTTP status code

**Comment by djcrawleravp** [comment]
Im geting this one...

Is that normal for this version?

<img width="416" alt="Screen Shot 2020-04-14 at 14 02 25" src="https://user-images.githubusercontent.com/12896341/79258185-c07f2000-7e58-11ea-9d52-e0396e38bd80.png">
