### ISSUE TITLE
Report font color

### ISSUE THREAD

**Issue by stranger29** [dutu/poloLender#74]
@dutu 
Could you please change report font color to something else? it's kinda unreadable if the background is black (see screenshot attached)
https://www.dropbox.com/s/hroeu1vihg55nhs/Screenshot%202017-06-19%2022.42.55.png?dl=0
Thank you.

**Comment by dutu** [comment]
@stranger29, would it be possible for you to change the background color of your console? Various people are using various background colors and it'll be a bit difficult to find colors to fit.

**Comment by stranger29** [comment]
@dutu 
Sure, I could definitely change it, but black  is used widely as a background color, I would say that  by default all mac users and windows putty/securecrt users have black background

**Comment by dutu** [comment]
changed in version 0.10.0. Let me know if acceptable

**Comment by stranger29** [comment]
Thanks, much better now !
