### ISSUE TITLE
Enhancement: Telegram bot

### ISSUE THREAD

**Issue by stranger29** [dutu/poloLender#76]
Hello, @dutu 
thank you for adding telegram bot, it's an amazing idea, however, please consider these changes:
Add ability to select different report interval for the telegram bot
Make sure report fits into one message.
Thank you

**Comment by dutu** [comment]
@stranger29 , the report interval is configurable through the env variable `POLOLENDER_REPORTINTERVAL`, which is setting the report interval both for Telegram and console log. Hope this is OK.

I'm afraid that sending the entire report as one message will make it less readable, especially if you are lending several currencies. I thought it would be better to report one coin per message (+ one other message for the summary on running time and total number of loans).
BTW, do you know you can mute a confersation in Telegram, so you don't get disturbed every time a new message arrive

**Comment by stranger29** [comment]
@dutu I parse console output so it's configured to report every 30 minutes. 
At the same time, I would like to get reports from bot every 6-12 hours and I don't want to have 20+ unread messages. So configurable bot report period would be really helpful.

**Comment by dutu** [comment]
added in version 0.10.0. 
Environment variable `POLOLENDER_TELEGRAM_REPORTINTERVAL` (in `.env` file when running locally) can be configured separately.

**Comment by stranger29** [comment]
So, I set it to 720 minutes
but I still get
"info: Using POLOLENDER_TELEGRAM_REPORTINTERVAL=60"
in console
However it looks like the setting was applied correctly
