### ISSUE TITLE
Can you add this variable?

### ISSUE THREAD

**Issue by tsebis** [dutu/poloLender#79]
Possible you add this variable? pololender_maxrate ?

**Comment by dutu** [comment]
what should be the use of it?

**Comment by tsebis** [comment]
Sometimes the bot opens loan orders with absurd rates, the book average is 0.15 for example, and the bot opens at 0.35 and takes a long time to lower, if it had the maxrate, we could change it to 0.25 so it would be borrowed faster

**Comment by dutu** [comment]
Lending and lower rates and faster would mean lending at sub-optimal rates.
See https://github.com/dutu/poloLender/issues/32 and [FAQ](https://github.com/dutu/poloLender/blob/master/faq.md)

**Comment by tsebis** [comment]
I have read this many times but it is better to have a guaranteed loan at 0.25 than to wait a long time for 0.35, and when you lend, the other user cancels in a few minutes

**Comment by tsebis** [comment]
See it, and have big walls, never will get 0.35
![image](https://user-images.githubusercontent.com/20957523/27332807-e0634f26-5599-11e7-92f4-a25d187fbf89.png)
![image](https://user-images.githubusercontent.com/20957523/27332833-f219d4ba-5599-11e7-92fd-7f295e59a78d.png)

**Comment by dutu** [comment]
@tsebis, statistically and in the long run it's not better. It may be better for a few occasions, but overall it is not better.

Do not worry the loan will move in front of the wall when it'll be more profitable to lend at lower rate.

I want to stay away from encouraging users to lend at non-optimal rates.
There are other popular bots which have this "feature" implemented, but firstly why would one want to lend an sub-optimal rates, secondly these bots lead to a race situation to have lower an lower lending rates.

**Comment by tsebis** [comment]
And if you add maxrate variable, can't be good for us?

**Comment by dutu** [comment]
No, it's mathematics, it can't be good :) 
Firstly it will be lending at sub-optimal lending and lower profitability, secondly it creates a race condition on on the lending book, which will lead to overall lower rates on Poloniex.

**Comment by tsebis** [comment]
But see, the time we have wasted waiting for someone to take our loan (which is practically double the current rate) we could have borrowed a few times, it takes hours to borrow at that rate .. well, if you think it's okay, just do not I know who is good .. so better to do manual, anyway, is a good job overall. Thank you

**Comment by dutu** [comment]
Very unlikely we couldn't have lent a few times since the average-loan-holding time is 3h30m.
For example in this case I'd rather wait for 1.5h to lend at double the rate

**Comment by tsebis** [comment]
It's been a while since it was 0.30, it's stabilized at 0.20 and the bot insists on opening at 0.36, the bad thing is that usually when we borrow a lot of rate, then the other part cancels quickly, so it's best to lend to 0.20 and always be borrowed, than only sometimes at 0.36, but ok, thank you anyway

**Comment by dutu** [comment]
your loan has just been taken at a  much higher rate :)

**Comment by Hansorb** [comment]
Hi Dutu,
I also have a question about loan rates. I have no way of contacting you through github other then this....
When the bot just get's started (npm start), does it need time to calculate a good rate to loan at?
It just "gave away" my money at 0.0203% @ 18:56 when there were much better rates to loan at, I think. For now I can only run the bot intermittent and would rather have it wait then to be hasty :)

**Comment by dutu** [comment]
The bot doesn't need time to calculate the rate, as it gets it from poloLender advisor. Until the information gets available from the poloLender advisor the rate is defaulted to max (5%)
