### ISSUE TITLE
Live trades tab empty

### ISSUE THREAD

**Issue by ericreber** [dutu/poloLender#81]
Hi,

I've setup poloLender Pro and I can see the trades in poliniex. But when I open the Live tab on the poloLender Bot page it only shows the string "Lives trades" and that it.
![capture](https://user-images.githubusercontent.com/472442/27386016-be552020-5694-11e7-8a80-e1e333f16b1e.PNG)

Do you know what I'm missing?

Thanks and regards,
Eric

**Comment by dutu** [comment]
@ericreber, this feature is not implemented yet. There is a PR https://github.com/dutu/poloLender/pull/73, which @patricktoerner is working on and hopefully it will be merged and released soon.

**Comment by ericreber** [comment]
Thanks for your fast answer. So currently the only way to see the loans done by the bot is in the console or is there an other way?

**Comment by dutu** [comment]
Yes, the console is the only way for now.
You can also setup telegram, so you can receive the reports on your telegram messenger (on your phone). Note that "info" messages for individual loans are not sent to Telegram, but only the reports.

For setting up Telegram messaging, please see the [FAQ](https://github.com/dutu/poloLender/blob/master/faq.md)

**Comment by ericreber** [comment]
Thanks for your help I've already setup Telegram thanks to the great FAQ provided on the main page.
Thanks for all the details.
