### ISSUE TITLE
New deposits

### ISSUE THREAD

**Issue by shaor0x** [dutu/poloLender#82]
Hi!
I have made a new deposit on my poloniex lending account, and the BOT counts it as profit.

How can i reset the BOT ? I tried deleting the folder and reinstalling the BOT, but it ddint work.

**Comment by tsebis** [comment]
Same here, Since first use, bot shows deposits as profits

**Comment by dutu** [comment]
You'd to update the config variable `POLOLENDER_STARTBALANCE`. Please see the readme file.

**Comment by tsebis** [comment]
I thought startbalance was the minimum to open an order. Thank you
