### ISSUE TITLE
Instructions, rename command

### ISSUE THREAD

**Issue by xR2** [dutu/poloLender#84]
Just wanted to point out that the instructions could be clear about the rename. If one tried to rename the file `.env-template to .env` under Windows it will not work. Windows requires a name for the file.

Using `git mv` in the git CMD terminal works perfectly.

**Comment by dutu** [comment]
@xR2, thanks for reporting and suggestion to improve the documentation. It will be included in the setup instruction

**Comment by dutu** [comment]
the suggested change has been included in version 0.11.0
