### ISSUE TITLE
Bug: Telegram bot report issues

### ISSUE THREAD

**Issue by stranger29** [dutu/poloLender#85]
Hello
I think there are couple bugs in telegram bot feature
POLOLENDER_TELEGRAM_REPORTINTERVAL set to 720 minutes
1)I still get "info: Using POLOLENDER_TELEGRAM_REPORTINTERVAL=60" in console on startup
2) No report after >800 minutes from startup

**Comment by dutu** [comment]
@stranger29 , thanks for the feedback.
1) issue with the message in the console is confirmed. A fix will be released in the next release
2) Please verify your Telegram token and user Id, the reports on telegram has not shown any issues. Please double check and will appreciate if you can give additional feedback on this

**Comment by stranger29** [comment]
@dutu,
1 - ok, thx.
2 - yep, my bad, somehow deleted one digit from my userid,
I think what could help here is on startup of the bot, lookup and show first/last name based on telegram id.

**Comment by dutu** [comment]
1. fixed in version 0.11.0
2. not possible to lookup the name based on telegram id
