### ISSUE TITLE
After updating the .env is gone

### ISSUE THREAD

**Issue by xR2** [dutu/poloLender#88]
It seems like after the last update my `.env` is gone. This doesn't look like how it's suppose to be, or is it?

**Comment by dutu** [comment]
Can you send the logs from when you updated? Or at least describe the steps you used?

**Comment by xR2** [comment]
Sure, just tell me where to find this logs,  lol.

I just follow as the instructions:

```
git fetch --all
git reset --hard origin/master

npm update

node server.js
```

**Comment by dutu** [comment]
Reason for your issue is the usage of `git mv` when you renamed `.env-template`. Please use `ren` instead.
