### ISSUE TITLE
Bot tried to cancel unowned loan offer.

### ISSUE THREAD

**Issue by eltherion** [dutu/poloLender#9]
Hi,
I got strange error in my log:
notice: returnAvailableAccountBalances: Poloniex error 500: Internal Server Error
notice: returnAvailableAccountBalances: Poloniex error 500: Internal Server Error
**notice: cancelLoanOffer: Error canceling loan order, or you are not the person who placed it. (#322231281)**
notice: returnActiveLoans: ESOCKETTIMEDOUT
notice: returnAvailableAccountBalances: Unknown error.
notice: returnOpenLoanOffers: Unknown error.
notice: returnActiveLoans: Poloniex error 500: Internal Server Error
notice: returnActiveLoans: ESOCKETTIMEDOUT
notice: returnActiveLoans: Poloniex error 500: Internal Server Error
notice: returnOpenLoanOffers: ESOCKETTIMEDOUT
notice: returnAvailableAccountBalances: ESOCKETTIMEDOUT
notice: returnOpenLoanOffers: Unknown error.
Do you know anything about such behaviour?

**Comment by dutu** [comment]
When the bot has to place an loan offers at a new rate, two API methods are called: 1) `returnOpenLoanOffers `and 2) `cancelLoanOffer`.

The API method `cancelLoanOffer` can return `Error canceling loan order, or you are not the person who placed it. ` if the loan offer is taken just immediately after `returnOpenLoanOffers ` is executed (i.e. in the very short interval between 1 and 2).

The message is classified as severity level "notice" which means "Events that are unusual, but not error conditions" (https://en.wikipedia.org/wiki/Syslog#Severity_level) - there is no impact on the good functionality of the bot.

**Comment by eltherion** [comment]
Thank you for fast response and explanation.
