### ISSUE TITLE
Error: Cannot find module 'asynckit'

### ISSUE THREAD

**Issue by lmk** [dutu/poloLender#91]
실행하면, Error: Cannot find module 'asynckit' 에러가 발생합니다.
poloLender$ npm install asynckit 하니까 제대로 돌아가네요.
package.json에 asynckit을 추가해야 할 듯합니다.

**Comment by dutu** [comment]
It looks that you need to run `npm update`.
When setting up/updating the application, follow the steps described in the readme file

**Comment by persona35** [comment]
I experienced same error like lmk.
I installed asynckit separately.

**Comment by dutu** [comment]
Have you done npm update as per instruction?

**Comment by persona35** [comment]
Yes. I did. I followed the instruction described in update section.

**Comment by dutu** [comment]
Do you perhaps still have a log? The application is not directly dependent on asynckit, any dependency should be installed by npm update

**Comment by persona35** [comment]
I'm not familiar with Ubuntu system, so I don't know where to find the log files.

If you let me know where I can find the log file, I will check and upload it.

**Comment by dutu** [comment]
@persona35, that would be the logs from the console where you installed the app.

Anyway, if you can try to reproduce the fault, a possible fix is to delete the file `package-lock.json`. See if this works.  (I had a similar issue in another project and deleting the file``package-lock.json` solved it)

**Comment by lmk** [comment]
I did an npm update, but "Can not find module 'asynckit'" occurred.

The error log is shown below.
```
PoloLender $ node ./server.js
Module.js: 487
     Throw err;
     ^

Error: Can not find module 'asynckit'
     At Function.Module._resolveFilename (module.js: 485: 15)
     At Function.Module._load (module.js: 437: 25)
     At Module.require (module.js: 513: 17)
     At require (internal / module.js: 11: 18)
     At Object. <Anonymous> (/home/newtype/poloLender/node_modules/request/node_modules/form-data/lib/form_data.js:9:16)
     At Module._compile (module.js: 569: 30)
     At Object.Module._extensions..js (module.js: 580: 10)
     At Module.load (module.js: 503: 32)
     At tryModuleLoad (module.js: 466: 12)
     At Function.Module._load (module.js: 458: 3)
```

**Comment by dutu** [comment]
a possible fix is to delete the file package-lock.json. See if this works.

**Comment by lmk** [comment]
Resolved. Thank you :-)
