### ISSUE TITLE
With what currencies does the bot work with?

### ISSUE THREAD

**Issue by vinipachecov** [dutu/poloLender#93]

**Comment by dutu** [comment]
![image](https://user-images.githubusercontent.com/6230798/27800628-e7f806da-6022-11e7-95f7-36ec35ce423c.png)

**Comment by vinipachecov** [comment]
Thank you, but how do I configure STR lendings?

**Comment by dutu** [comment]
just need to add STR to your `POLOLENDER_STARTBALANCE` env variable 
example:
`POLOLENDER_STARTBALANCE={"STR":"1000"}`

**Comment by vinipachecov** [comment]
Do I need to put it on MINRATE?

My file is like this:

# Start UTC time - this is used to calculate and display total profitability
POLOLENDER_STARTTIME=2016-02-28T12:27:09+00:00

# Start balance - this is used to calculate and display total profitability
POLOLENDER_STARTBALANCE={"BTC":"10", "ETH":"1100", "XMR":"1000","STR":"100" }

# Maximum amounts in your lending account that should be lended
POLOLENDER_LENDMAX={"BTC":"900", "ETH":"99900", "XMR":"2000"}

# Minimum lending rate in percent.
POLOLENDER_MINRATE={"BTC":"0.08", "ETH":"0", "XMR":"0", "XRP":"0", "LTC":"0", "STR":"0.08"}

#Report interval in minutes (default is 60 minutes)
POLOLENDER_REPORTINTERVAL=30

**Comment by dutu** [comment]
That should be ok.

* in `POLOLENDER_STARTBALANCE` you should only keep the currencies with the balances you have in your funding account

* if you specify minrate > 0, the bot will not lend if rate drops below that value.

**Comment by vinipachecov** [comment]
Thank you, I think that's all!
