### ISSUE TITLE
Please fix doge rate fixed

### ISSUE THREAD

**Issue by ergo9ine** [dutu/poloLender#94]
It does not function normally.
Ex : 
info: OfferCanceled #502068560 DOGE 1007669.56425313 at 0.409999%, brr 0.413598%
info: Loan offered  #502070713 DOGE 1007669.56425313 at 0.413598%, duration 2 days
info: OfferCanceled #502070713 DOGE 1007669.56425313 at 0.413598%, brr 0.409999%
info: Loan offered  #502070967 DOGE 1007669.56425313 at 0.409999%, duration 2 days

**Comment by dutu** [comment]
@TypeNine, I'm not sure why do you think something is wrong.
Please have a look at the FAQ, it gives some insights on how the best return rate is calculated.

Please also note that during the last several hours DOGE had several spikes in lending rates, see example below (which is from the database the engine is using), hence the engine trying to lend at high rates is expected.

![image](https://user-images.githubusercontent.com/6230798/27796393-86ca5440-6012-11e7-9865-918196acacc1.png)

**Comment by ergo9ine** [comment]
@dutu thx 
One more question.
What the "brr 5.000000%"

**Comment by dutu** [comment]
When there is no info from the advisor server, the app sets the rate to maximum rate which is 5%.
This situation can occur just after you started the app, until it gets connection and information from the advisor server (usually a couple of seconds)
