### ISSUE TITLE
Did you make it?

### ISSUE THREAD

**Issue by ergo9ine** [dutu/poloLender#95]
I think the source code was stolen.
https://play.google.com/store/apps/details?id=tk.henriqueormonde.CryptoCurr

**Comment by dutu** [comment]
@TypeNine , thanks for the feedback.

* poloLender Pro app is open source under [MIT](https://github.com/dutu/poloLender/blob/master/LICENSE) license, hence it can be copied, modified and distributed.

* There are a number of Poloniex lending apps on the internet. poloLender Pro has unique features, which make it more profitable than other bots

* From the app description and available parameters on the link you mentioned, it can be noticed that lending engine is weak and cannot reach high profitability
