### ISSUE TITLE
0.12.0-beta1 error log

### ISSUE THREAD

**Issue by ergo9ine** [dutu/poloLender#97]
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! poloLenderPro@0.12.0-beta1 start: `node -r babel-register app.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the poloLenderPro@0.12.0-beta1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by ergo9ine** [comment]
> 0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@5.0.3
3 info using node@v8.1.3
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle poloLenderPro@0.12.0-beta1~prestart: poloLenderPro@0.12.0-beta1
6 silly lifecycle poloLenderPro@0.12.0-beta1~prestart: no script for prestart, continuing
7 info lifecycle poloLenderPro@0.12.0-beta1~start: poloLenderPro@0.12.0-beta1
8 verbose lifecycle poloLenderPro@0.12.0-beta1~start: unsafe-perm in lifecycle true
9 verbose lifecycle poloLenderPro@0.12.0-beta1~start: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;C:\Users\com1\pololender\node_modules\.bin;C:\Users\com1\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\local\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Users\com1\bin;C:\windows\system32;C:\windows;C:\windows\System32\Wbem;C:\windows\System32\WindowsPowerShell\v1.0;C:\ProgramData\GooGet;C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\bin;C:\Program Files\Google\Compute Engine\metadata_scripts;C:\Program Files\Google\Compute Engine\sysprep;C:\Program Files\nodejs;C:\Program Files\Git\cmd;C:\Users\com1\AppData\Local\Microsoft\WindowsApps;C:\Users\com1\AppData\Roaming\npm;C:\Program Files\Git\usr\bin\vendor_perl;C:\Program Files\Git\usr\bin\core_perl
10 verbose lifecycle poloLenderPro@0.12.0-beta1~start: CWD: C:\Users\com1\pololender
11 silly lifecycle poloLenderPro@0.12.0-beta1~start: Args: [ '/d /s /c', 'node -r babel-register app.js' ]
12 silly lifecycle poloLenderPro@0.12.0-beta1~start: Returned: code: 1  signal: null
13 info lifecycle poloLenderPro@0.12.0-beta1~start: Failed to exec start script
14 verbose stack Error: poloLenderPro@0.12.0-beta1 start: `node -r babel-register app.js`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:283:16)
14 verbose stack     at emitTwo (events.js:125:13)
14 verbose stack     at EventEmitter.emit (events.js:213:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:125:13)
14 verbose stack     at ChildProcess.emit (events.js:213:7)
14 verbose stack     at maybeClose (internal/child_process.js:897:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:208:5)
15 verbose pkgid poloLenderPro@0.12.0-beta1
16 verbose cwd C:\Users\com1\pololender
17 verbose Windows_NT 10.0.14393
18 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
19 verbose node v8.1.3
20 verbose npm  v5.0.3
21 error code ELIFECYCLE
22 error errno 1
23 error poloLenderPro@0.12.0-beta1 start: `node -r babel-register app.js`
23 error Exit status 1
24 error Failed at the poloLenderPro@0.12.0-beta1 start script.
24 error This is probably not a problem with npm. There is likely additional logging output above.
25 verbose exit [ 1, true ]

**Comment by dutu** [comment]
@TypeNine thanks a lot for submitting this issue. The beta releases from `dev` branch are not fully developed and tested, but I appreciate your feedback on this and will look into the issue raised.

**Comment by dutu** [comment]
you can try the new beta release from `dev` branch and let me know how it goes. 
When running it, please follow the instruction in the readme file. (This release introduces significant changes, such as the settings are only configurable from the web GUI - previews configuration file and environment variable become obsolete)

**Comment by ergo9ine** [comment]
Thx!!!

**Comment by dutu** [comment]
Please use version 1.0.0 that has just been released and let me know if still any issues
